# Generated by Django 3.1.4 on 2021-01-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20201230_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='englishtest',
            name='result',
            field=models.CharField(blank=True, choices=[('AT', 'Attended'), ('S', 'Succeeded'), ('F', 'Failed'), ('P', 'Postponed'), ('A', 'Absent'), ('L', 'Low Score'), ('U', 'Unkown Certificate')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='result',
            field=models.CharField(blank=True, choices=[('AT', 'Attended'), ('S', 'Succeeded'), ('F', 'Failed'), ('P', 'Postponed'), ('A', 'Absent'), ('L', 'Low Score'), ('U', 'Unkown Certificate')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveIntegerField(choices=[(1, 'Register Student'), (2, 'Admission Department'), (3, 'English Department'), (4, 'Scholarships Department'), (5, 'Supervisor Department'), (6, 'Register Dean'), (7, 'Pharmacy Dean'), (8, 'Communication Department'), (9, 'Medicine Dean'), (10, 'Science Dean'), (11, 'Register Review'), (12, 'English Confirmer'), (13, 'Interview Test'), (90, 'Super Admin')]),
        ),
    ]

