# Generated by Django 3.1.3 on 2021-01-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_absent'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='status_m',
            field=models.BooleanField(default=True),
        ),
    ]
