# Generated by Django 3.2 on 2021-04-17 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_applicant_final_state_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='univpayments',
            name='payment_title',
            field=models.CharField(choices=[('ERET', 'english_retest'), ('REG', 'registration_fees'), ('EQU', 'Equation Fees')], max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveIntegerField(choices=[(1, 'Register Student'), (2, 'Admission Department'), (3, 'English Department'), (4, 'Scholarships Department'), (5, 'Supervisor Department'), (6, 'Admission Manager'), (7, 'Pharmacy Dean'), (8, 'Communication Department'), (9, 'Medicine Dean'), (10, 'Science Dean'), (11, 'Register Review'), (12, 'English Confirmer'), (13, 'Interview Test'), (14, 'Equation Supervisor'), (90, 'Super Admin')]),
        ),
    ]
