# Generated by Django 3.2 on 2021-06-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_auto_20210608_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_major',
            field=models.CharField(blank=True, choices=[('MS', 'Medicine & Surgery'), ('PHD', 'Pharm D'), ('NU', 'Nursing'), ('RT', 'Respiratory Therapy'), ('EMS', 'Emergency Medical Services'), ('AT', 'Anaesthesia Technology'), ('HIS', 'Health Information Systems'), ('IS', 'Information Systems'), ('CS', 'Computer Science'), ('IE', 'Industrial Engineering'), ('GSE', 'General science & English'), ('M', 'Medicine'), ('PH', 'Pharmacy'), ('AS', 'Applied Science')], max_length=10, null=True),
        ),
    ]
