# Generated by Django 3.2 on 2021-06-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_reservation_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='englishtest',
            name='entry_user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
