# Generated by Django 3.2 on 2021-06-15 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_englishtest_entry_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='english_certf_entry_user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
