# Generated by Django 3.2 on 2021-06-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0015_applicant_english_certf_entry_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='englishtest',
            name='notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
