# Generated by Django 3.2 on 2021-06-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0016_alter_englishtest_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='equation_fees_exempt',
            field=models.BooleanField(default=False),
        ),
    ]
