# Generated by Django 3.2 on 2021-11-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0019_auto_20211025_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='duration_time',
            field=models.FloatField(default=1),
        ),
    ]
