# Generated by Django 3.2 on 2021-11-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0020_alter_reservation_duration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='birth_date_hegry',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
