# Generated by Django 3.1.3 on 2022-07-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0023_auto_20220515_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
