# Generated by Django 3.1.3 on 2023-04-24 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0024_auto_20220719_1645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['city_no']},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['country_no']},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['school_no']},
        ),
        migrations.RenameField(
            model_name='city',
            old_name='city_name_englsih',
            new_name='city_name_english',
        ),
    ]
