# Generated by Django 3.1.3 on 2023-04-24 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0025_auto_20230424_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_no', models.IntegerField(blank=True, null=True)),
                ('city_no', models.IntegerField(blank=True, null=True)),
                ('country_no', models.IntegerField(blank=True, null=True)),
                ('zone_name_english', models.CharField(blank=True, max_length=300, null=True)),
                ('zone_name_arabic', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'zone',
                'ordering': ['zone_no'],
            },
        ),
        migrations.AddField(
            model_name='school',
            name='zone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
