# Generated by Django 3.1.3 on 2023-05-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0026_auto_20230424_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='sat_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
