# Generated by Django 3.1.3 on 2023-05-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0027_applicant_sat_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('A', 'All')], max_length=1),
        ),
    ]
