# Generated by Django 3.1.3 on 2023-06-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0029_auto_20230608_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='english_certf_result',
            field=models.CharField(blank=True, choices=[('S', 'Succeeded'), ('F', 'Failed'), ('L', 'Low Score'), ('U', 'Unkown Certificate')], max_length=3, null=True),
        ),
    ]
