# Generated by Django 3.1.3 on 2023-06-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0030_auto_20230609_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='arabic_full_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='full_name',
            field=models.CharField(max_length=200),
        ),
    ]
