# Generated by Django 3.1.3 on 2023-06-13 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0032_auto_20230612_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOracleProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_id', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('national_id', models.CharField(max_length=100)),
                ('process', models.SmallIntegerField(choices=[(1, 'Registration Payment'), (2, 'Retest Payment')])),
                ('transaction_id', models.CharField(max_length=200)),
                ('send', models.BooleanField(default=False)),
                ('send_date', models.DateTimeField(blank=True, null=True)),
                ('delivered', models.BooleanField(default=False)),
                ('delivered_date', models.DateTimeField(blank=True, null=True)),
                ('number_tries', models.SmallIntegerField(default=0)),
                ('error_reason', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='School',
        ),
        migrations.DeleteModel(
            name='Zone',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='eightth_periority',
            new_name='eighth_periority',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='nineth_periority',
            new_name='ninth_periority',
        ),
        migrations.AlterField(
            model_name='applicant',
            name='english_certf_result',
            field=models.CharField(blank=True, choices=[('S', 'Succeeded'), ('F', 'Failed'), ('L', 'Low Score'), ('U', 'Unknown Certificate')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='englishtest',
            name='test_type',
            field=models.CharField(blank=True, choices=[('T', 'TOEFL'), ('I', 'IELTS'), ('OX', 'Oxford'), ('S', 'Step')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='oracleprocess',
            name='process',
            field=models.SmallIntegerField(choices=[(1, 'Add Applicant'), (2, 'Update Applicant'), (3, 'Update Score'), (4, 'Add Major'), (5, 'Update Major'), (6, 'Update Payment')]),
        ),
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.PositiveIntegerField(choices=[(1, 'Applicant'), (2, 'Admission Department'), (3, 'English Department'), (4, 'Scholarships Department'), (5, 'Supervisor Department'), (6, 'Admission Manager'), (7, 'Pharmacy Dean'), (8, 'Communication Department'), (9, 'Medicine Dean'), (10, 'Science Dean'), (11, 'Register Review'), (12, 'English Conformer'), (13, 'Interview Test'), (14, 'Equation Supervisor'), (15, 'Head Of Department'), (90, 'Super Admin')], unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveIntegerField(choices=[(1, 'Applicant'), (2, 'Admission Department'), (3, 'English Department'), (4, 'Scholarships Department'), (5, 'Supervisor Department'), (6, 'Admission Manager'), (7, 'Pharmacy Dean'), (8, 'Communication Department'), (9, 'Medicine Dean'), (10, 'Science Dean'), (11, 'Register Review'), (12, 'English Conformer'), (13, 'Interview Test'), (14, 'Equation Supervisor'), (15, 'Head Of Department'), (90, 'Super Admin')]),
        ),
    ]
