# Generated by Django 3.1.3 on 2023-06-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0033_auto_20230613_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentoracleprocess',
            name='process',
            field=models.SmallIntegerField(choices=[(1, 'Registration Payment'), (2, 'Retest Payment'), (3, 'Equation Payment')]),
        ),
    ]
