# Generated by Django 3.1.3 on 2023-06-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0035_auto_20230613_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentoracleprocess',
            name='process',
            field=models.CharField(choices=[('ERET', 'english_retest'), ('REG', 'registration_fees'), ('EQU', 'Equation Fees')], max_length=100),
        ),
    ]
