# Generated by Django 3.1.3 on 2023-06-19 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0036_auto_20230614_0851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, max_length=1000, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('applicant_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_applicant', to='registration.applicant')),
                ('modified_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
