# Generated by Django 3.1.3 on 2023-06-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0037_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oracleprocess',
            name='process',
            field=models.SmallIntegerField(choices=[(1, 'Add Applicant'), (2, 'Update Applicant'), (3, 'Update Score'), (4, 'Add Major'), (5, 'Update Major')]),
        ),
        migrations.AlterField(
            model_name='univpayments',
            name='cost',
            field=models.FloatField(),
        ),
    ]
