# Generated by Django 3.1.3 on 2023-07-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0038_auto_20230621_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=2, null=True),
        ),
    ]
