# Generated by Django 3.1.3 on 2023-07-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0039_reservation_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='englishtest',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
