# Generated by Django 3.1.3 on 2023-07-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0041_auto_20230708_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='arabic_family_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='arabic_first_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='arabic_full_name',
            field=models.CharField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='arabic_last_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='arabic_middle_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='family_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='first_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='full_name',
            field=models.CharField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='last_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='middle_name',
            field=models.CharField(max_length=500),
        ),
    ]
