# Generated by Django 3.1.3 on 2023-08-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0042_auto_20230708_1909'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversationparticipants',
            options={'verbose_name': 'Conversation Participant', 'verbose_name_plural': 'Conversation Participants'},
        ),
        migrations.AlterModelOptions(
            name='files',
            options={'verbose_name': 'File', 'verbose_name_plural': 'Files'},
        ),
        migrations.AlterModelOptions(
            name='messageparticipants',
            options={'verbose_name': 'Message Participant', 'verbose_name_plural': 'Message Participants'},
        ),
        migrations.AlterModelOptions(
            name='oracleprocess',
            options={'verbose_name': 'Oracle Process', 'verbose_name_plural': 'Oracle Processes'},
        ),
        migrations.AlterModelOptions(
            name='participants',
            options={'verbose_name': 'Participant', 'verbose_name_plural': 'Participants'},
        ),
        migrations.AlterModelOptions(
            name='paymentoracleprocess',
            options={'verbose_name': 'Payment Oracle Process', 'verbose_name_plural': 'Payment Oracle Processes'},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name': 'University', 'verbose_name_plural': 'Universities'},
        ),
        migrations.AlterField(
            model_name='applicant',
            name='english_certf_confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
