# Generated by Django 3.1.3 on 2023-08-14 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0045_payment_by_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_confirmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
