# Generated by Django 3.1.3 on 2023-08-31 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0046_payment_payment_confirmer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='englishtest',
            name='test_try',
            field=models.SmallIntegerField(choices=[(1, 'First Test'), (2, 'Second Test'), (3, 'Third Test')]),
        ),
    ]
