# Generated by Django 3.1.3 on 2023-11-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0047_auto_20230831_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='degree',
            field=models.CharField(choices=[('UG', 'Bachelors'), ('PG', 'Masters')], default='UG', max_length=50),
        ),
        migrations.AddField(
            model_name='applicant',
            name='emergency_qualification',
            field=models.CharField(choices=[('UE', 'Uneducated'), ('EL', 'Elementary'), ('INT', 'Intermediate'), ('HS', 'High school'), ('DP', 'Diploma'), ('UG', 'Bachelors'), ('PG', 'Masters'), ('DR', 'Doctors')], default='UE', max_length=20),
        ),
        migrations.AddField(
            model_name='applicant',
            name='superior_qualification',
            field=models.CharField(choices=[('UE', 'Uneducated'), ('EL', 'Elementary'), ('INT', 'Intermediate'), ('HS', 'High school'), ('DP', 'Diploma'), ('UG', 'Bachelors'), ('PG', 'Masters'), ('DR', 'Doctors')], default='UE', max_length=20),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='arabic_speaker',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='major',
            name='name',
            field=models.CharField(choices=[('MS', 'Medicine & Surgery'), ('PHD', 'Pharm D'), ('NU', 'Nursing'), ('RT', 'Respiratory Therapy'), ('EMS', 'Emergency Medical Services'), ('AT', 'Anaesthesia Technology'), ('HIS', 'Health Information Systems'), ('IS', 'Information Systems'), ('CS', 'Computer Science'), ('IE', 'Industrial Engineering'), ('GSE', 'General science & English'), ('MEDN', 'Master of Emergency and Disaster Nursing'), ('MCP', 'Master of Clinical Pharmacy'), ('MCS', 'Master of Cyber Security'), ('NM', 'No Major')], max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_major',
            field=models.CharField(blank=True, choices=[('MS', 'Medicine & Surgery'), ('PHD', 'Pharm D'), ('NU', 'Nursing'), ('RT', 'Respiratory Therapy'), ('EMS', 'Emergency Medical Services'), ('AT', 'Anaesthesia Technology'), ('HIS', 'Health Information Systems'), ('IS', 'Information Systems'), ('CS', 'Computer Science'), ('IE', 'Industrial Engineering'), ('GSE', 'General science & English'), ('M', 'Medicine'), ('PH', 'Pharmacy'), ('AS', 'Applied Science'), ('MEDN', 'Master of Emergency and Disaster Nursing'), ('MCP', 'Master of Clinical Pharmacy'), ('MCS', 'Master of Cyber Security'), ('NM', 'No Major')], max_length=10, null=True),
        ),
    ]
