# Generated by Django 3.1.3 on 2023-11-20 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0048_auto_20231118_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('HS', 'High School Certificate'), ('AC', 'Certified Academic Record'), ('BDC', 'Bachelor Degree Certificate'), ('DC', 'Diploma Certificate'), ('IC', 'Certificate of Completion Internship')], max_length=100, null=True)),
                ('status', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_applicant', to='registration.applicant')),
                ('approve_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approve_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
