# Generated by Django 3.1.3 on 2023-11-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0049_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='certificate_status',
            field=models.CharField(blank=True, choices=[('NS', 'Not Submitted'), ('PS', 'Partially Submitted'), ('FS', 'Fully Submitted')], max_length=10, null=True),
        ),
    ]
