# Generated by Django 3.2 on 2021-04-17 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import equations.models.equations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0009_auto_20210418_0158'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversirtyCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('course_no', models.IntegerField(unique=True)),
                ('arabic_name', models.CharField(max_length=75)),
                ('code', models.CharField(max_length=20)),
                ('arabic_code', models.CharField(max_length=20)),
                ('hours', models.SmallIntegerField()),
                ('faculty', models.SmallIntegerField(choices=[(1, 'Medicine'), (2, 'Pharmacy'), (3, 'Applied Science')])),
            ],
        ),
        migrations.CreateModel(
            name='EquivalentCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('code', models.CharField(max_length=20)),
                ('hours', models.SmallIntegerField()),
                ('equivalent_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equations.universirtycourse')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.university')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('university', 'equivalent_to', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Equation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('init_state', models.CharField(choices=[('UR', 'Under Review'), ('IA', 'Initial Acceptance'), ('AC', 'Accepted'), ('NM', 'Need Modification'), ('RJ', 'Rejected')], default='UR', max_length=3)),
                ('final_state', models.CharField(blank=True, choices=[('UR', 'Under Review'), ('IA', 'Initial Acceptance'), ('AC', 'Accepted'), ('NM', 'Need Modification'), ('RJ', 'Rejected')], max_length=3, null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('equation_file', models.FileField(blank=True, null=True, upload_to=equations.models.equations.get_image_filename)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equation_applicants', to='registration.applicant')),
                ('equation_courses', models.ManyToManyField(blank=True, to='equations.EquivalentCourse')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
