# Generated by Django 3.2 on 2021-06-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equations', '0002_auto_20210422_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='equivalentcourse',
            name='exception',
            field=models.BooleanField(default=False),
        ),
    ]
