# Generated by Django 3.2 on 2021-07-04 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equations', '0003_equivalentcourse_exception'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='equivalentcourse',
            unique_together=set(),
        ),
    ]
