# Generated by Django 3.1.3 on 2022-05-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equations', '0007_auto_20211117_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='equation',
            name='head_of_department_state',
            field=models.CharField(blank=True, choices=[('UR', 'Under Review'), ('IA', 'Initial Acceptance'), ('AC', 'Accepted'), ('NM', 'Need Modification'), ('RJ', 'Rejected')], max_length=3, null=True),
        ),
    ]
