# Generated by Django 3.1.3 on 2023-08-01 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equations', '0008_equation_head_of_department_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='universirtycourse',
            options={'verbose_name': 'University Course', 'verbose_name_plural': 'University Courses'},
        ),
    ]
