# Generated by Django 3.1.3 on 2020-11-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TokenList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('full_name', models.CharField(max_length=50)),
                ('user_type', models.CharField(max_length=50)),
                ('token', models.CharField(editable=False, max_length=300, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
