# Generated by Django 3.1.3 on 2023-07-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0002_tokenlist_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenlist',
            name='full_name',
            field=models.CharField(max_length=2500),
        ),
    ]
